version: '3.8'

services:
  web:
    restart: always
    build: ./xway
    command: gunicorn xway.wsgi:application --bind 0.0.0.0:8888
    volumes:
      - ./xway/:/usr/src/app/
    ports:
      - 8888:8888
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    env_file:
      - .env.dev
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql13.0/data/
    environment:
      - POSTGRES_USER=$${POSTGRES_USER}
      - POSTGRES_PASSWORD=$${POSTGRES_PASSWORD}
      - POSTGRES_DB=$${POSTGRES_DB}
volumes:
  postgres_data: